services:
  postgres-container:
    image: postgres
    restart: no
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - .postgresql:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
  redis-container:
    image: redis
    restart: no
    ports:
      - '6379:${REDIS_PORT}'
    volumes:
      - .redis:/data
    environment:
      REDIS_PORT: ${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    env_file:
      - .env